feat: enable redis layers automatic addition to config
MapColonies/mapproxy-api pull request #107
Opened 2023-12-12 18:20 UTC by razbroc

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2023-12-12 22:03 UTC, shimoncohen commented
Please fix PR title to fit `commitlint` format and be more precise.

2023-12-13 00:08 UTC, shimoncohen requested changes

2023-12-13 19:14 UTC, shimoncohen commented on src/layers/models/layersManager.ts
> +          jsonDocument.caches[`${redisLayerName}`] = redisCache;
It is not really fixed because the `else` still exists. You should refactor this as mentioned.

2023-12-13 19:15 UTC, shimoncohen commented on src/layers/models/layersManager.ts
> +      const negativeResult = -1;
This doesn't help readability, it is not needed. It's not a magic number, please remove it.

2023-12-13 19:17 UTC, shimoncohen commented on src/layers/models/layersManager.ts
> +        const redisCacheName: string = cacheName.slice(-7);
You can leave this only row if you move the condition after you declare and assign default values. Please make the changes.

2023-12-13 19:19 UTC, shimoncohen submitted a review, later dismissed

2023-12-13 19:19 UTC, shimoncohen commented on src/layers/models/layersManager.ts
> +
Please remove extra empty lines.

2023-12-28 10:58 UTC, asafMasa requested changes
Good Job 👍

2023-12-28 10:58 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    const isRedisEnabled = config.get<boolean>('redis.enabled');
get this in contructor - no need to resolve this every time this method is called

2023-12-28 10:58 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    //creates source cache+redis cache, and a redis layer
add info log of adding new redis layer with their params

2023-12-28 10:58 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    //creates source cache, and a source layer
add info log of adding new source layer with their params

2023-12-28 10:58 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +          if (linkedCaches.indexOf(currentCache) == -1) {
Why don't you use other methods such as incldes and find? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2023-12-28 10:58 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +        if (requestedLayerIndex !== -1) {
Why don't you use other methods such as incldes and find? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2023-12-28 10:58 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +      if (requestedLayerIndex !== -1) {
why don't you use Find?

2023-12-28 10:58 UTC, asafMasa commented on tests/integration/layers/layersManager.spec.ts
> +          { layerName: 'NameIsAlreadyExists-source', zIndex: 0 },
please add integration tests for adding, updating and deleting redis layer

2023-12-28 10:58 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      const resource: IMapProxyCache = await layersManager.getLayer('mockLayerNameExists-source');
please add unit tests for the section that decides if to use redis layer and other methods if needed

2024-01-01 06:58 UTC, asafMasa commented on config/custom-environment-variables.json
> +      "enableRedisUser": {
you forgot to change the config/default.json file...

2024-01-01 07:02 UTC, asafMasa commented on src/common/cacheProviders/redisSource.ts
> +import { Logger } from '@map-colonies/js-logger';
wasn't fixed

2024-01-01 12:57 UTC, asafMasa requested changes

2024-01-01 12:57 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +  isRedisEnabled = config.get<boolean>('redis.enabled');
move to ctor

2024-01-21 07:28 UTC, asafMasa commented on src/common/cacheProviders/redisSource.ts
> +import { Logger } from '@map-colonies/js-logger';
wasn't fixed again...

2024-01-21 08:22 UTC, asafMasa requested changes

2024-01-21 08:22 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +        if (requestedLayerIndex !== -1) {
failedLayers = layersName.filter((x) => !allLinkedCaches.includes(x));

please change 'x' to meaningful name

2024-01-21 08:22 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      expect(myCreateRedisCache).toHaveBeenCalled();
why don't you check the updated values?

2024-01-21 08:22 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      const resource: IMapProxyCache = await layersManager.getLayer('redisExists');
do you check 'redis not Exists' layer?

2024-01-23 07:50 UTC, asafMasa requested changes

2024-01-23 07:50 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +  private addNewCache(jsonDocument: IMapProxyJsonDocument, layerRequest: ILayerPostRequest): void {
please separate between methods with line separator

2024-01-23 07:50 UTC, asafMasa commented on helm/templates/configmap.yaml
> +  S3_ENDPOINT_URL: {{ quote .Values.rasterCommon.storage.s3.endpointUrl }}
Update by new helm definitions (rasterCommon is obselete)

2024-01-23 07:50 UTC, asafMasa commented on src/common/cacheProviders/redisSource.ts
> +    this.sourceCacheType = SourceTypes.REDIS;
rename to redisSourceCacheType

2024-01-23 07:50 UTC, asafMasa commented on src/common/cacheProviders/redisSource.ts
> +      this.logger.error('configuration is missing redis parameters');
please log the err exception {err: err, msg: '...'}

2024-01-23 07:50 UTC, asafMasa commented on src/common/interfaces.ts
> +export interface IRedisConfig {
add line separator between interfaces

2024-01-23 07:50 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    this.logger.info(`adding ${layerRequest.name} as redis layer`);
why duplicate logs?

2024-01-23 07:50 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      expect(result.caches[mockLayerName].format).toBe(TileFormat.JPEG);
you should assert it to be PNG before the update operation is called in the test

2024-01-23 07:50 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      const mockLayerName = 'mockLayerNameExists-source';
you should assert params before and after the update

2024-01-23 07:50 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      const mockNotExistsLayerNames = ['mockLayerNameIsNotExists-source', 'anotherMockLayerNameNotExists'];
you should assert layer don't exists before the delete

2024-01-23 07:50 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      const action = layersManager.removeLayer(mockLayerNames);
you should assert layer and redis exists before the delete

2024-01-23 07:50 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      const mockLayerNames = ['mockLayerNameExists-source', 'NameIsAlreadyExists-source'];
you should assert layerexists before the delete

2024-01-23 07:50 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      name: 'amsterdam_5cm-source',
?

2024-01-23 07:50 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      const result = await MockConfigProvider.getJson();
why don't you check more params?

2024-01-23 10:35 UTC, asafMasa approved these changes

2024-01-24 09:28 UTC, merged