feat: added implementation to reorder mosaic layers
MapColonies/mapproxy-api pull request #16
Opened 2021-01-27 14:25 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                       |
| Breaking change |✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                      |
| Chore            | ✔                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-01-27 16:21 UTC, asafMasa requested changes
👍

2021-01-27 16:21 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +      throw new NoContentError(`Mosaic name '${reorderMosaicRequest.mosaicName}' is not exists`);
NoContentError - consider using 404

2021-01-27 16:21 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +        throw new NoContentError(`layer name '${layer.layerName}' is not exists`);
NoContentError - consider using 404

2021-01-27 16:36 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +        throw new NoContentError(`layer name '${layer.layerName}' is not exists`);
fixed in ceb8c7c

2021-01-27 16:36 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +      throw new NoContentError(`Mosaic name '${reorderMosaicRequest.mosaicName}' is not exists`);
fixed in ceb8c7c

2021-01-27 16:36 UTC, CL-SHLOMIKONCHA commented on src/common/utils.ts
> +    sortedArray.forEach((layer) => {
fixed in ceb8c7c

2021-01-28 07:48 UTC, asafMasa requested changes

2021-01-28 07:48 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    const jsonDocument: IMapProxyJsonDocument = convertYamlToJson(this.mapproxyConfig.yamlFilePath);
add all error types to openapi

2021-01-28 08:07 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +    const jsonDocument: IMapProxyJsonDocument = convertYamlToJson(this.mapproxyConfig.yamlFilePath);
fixed in e8b20a3

2021-01-28 08:32 UTC, asafMasa approved these changes

2021-01-28 08:35 UTC, merged