feat(server): added layers controller skeleton and utils skeleton
MapColonies/mapproxy-api pull request #4
Opened 2021-01-12 16:32 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-01-12 17:00 UTC, asafMasa requested changes

2021-01-13 07:35 UTC, CL-SHLOMIKONCHA commented on src/resourceName/models/layersManager.ts
> +const mockLayer: LayerPostRequest = {
fixed in 785be83

2021-01-13 07:36 UTC, CL-SHLOMIKONCHA commented on src/resourceName/models/layersManager.ts
> +    this.logger.log('info', newLayer.name);
fixed in 4fc26a6

2021-01-13 08:27 UTC, asafMasa approved these changes

2021-01-13 08:27 UTC, merged