feat: added default config file
MapColonies/mapproxy-api pull request #43
Opened 2021-03-01 11:24 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                     |
| Chore            | ✔                                                                       |

-->

2021-03-01 14:42 UTC, asafMasa requested changes

2021-03-01 14:42 UTC, asafMasa commented on config/default.json
> +      "endpoint_url": "http://localhost:9000",
camelCase for all of the config file

2021-03-01 14:42 UTC, asafMasa commented on src/common/interfaces.ts
> +}
press enter

2021-03-01 14:42 UTC, asafMasa commented on src/initConfig.ts
> +  const mapproxyConfig: IMapProxyConfig = container.resolve(Services.MAPPROXY);
refactor mapproxyConfig

2021-03-02 09:10 UTC, CL-SHLOMIKONCHA commented on src/common/interfaces.ts
> +}
fixed in 3d6efa8

2021-03-02 09:10 UTC, CL-SHLOMIKONCHA commented on config/default.json
> +      "endpoint_url": "http://localhost:9000",
fixed in 6795f27

2021-03-02 09:10 UTC, CL-SHLOMIKONCHA commented on src/initConfig.ts
> +  const mapproxyConfig: IMapProxyConfig = container.resolve(Services.MAPPROXY);
fixed in eec1158

2021-03-02 12:43 UTC, asafMasa approved these changes

2021-03-02 12:43 UTC, merged