feat: added fs cache dir support as source
MapColonies/mapproxy-api pull request #69
Opened 2021-07-12 13:51 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✔                                                                     |

2021-07-13 05:47 UTC, CL-SHLOMIKONCHA commented on src/common/enums/sourceTypes.ts
> +  FS = 'file',
its 'file' - because mapproxy defined this value as file system "cache dir" inside the yaml file

2021-07-13 06:41 UTC, asafMasa requested changes

2021-07-13 12:30 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +      throw new Error('Invalid source provider due to invalid source path, available values: "geopackage", "s3", "file"');
added in 
f0ab226

2021-07-13 12:30 UTC, CL-SHLOMIKONCHA commented on openapi3.yaml
> +          type: string
fixed in 
c31e262

2021-07-13 15:24 UTC, asafMasa requested changes

2021-07-13 15:24 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    if (cacheSource === SourceTypes.GPKG) {
why not to use switch?

2021-07-14 06:03 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +    if (cacheSource === SourceTypes.GPKG) {
fixed in 9f1cc68

2021-07-14 06:48 UTC, asafMasa approved these changes

2021-07-14 06:48 UTC, merged