feat: added layer controller base logic + fixed error handler
MapColonies/mapproxy-api pull request #8
Opened 2021-01-14 13:06 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | /✖                                                                        |
| New feature     | ✔/                                                                       |
| Breaking change | /✖                                                                        |
| Deprecations    | /✖                                                                        |
| Documentation   | /✖                                                                        |
| Tests added     | /✖                                                                        |
| Chore            | ✔                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-01-14 14:52 UTC, asafMasa requested changes
🚀 Good Job

2021-01-14 14:52 UTC, asafMasa commented on src/resourceName/models/layersManager.ts
> +    replaceYamlFileContent(yamlContent);
add log on completion

2021-01-14 14:52 UTC, asafMasa commented on src/resourceName/models/layersManager.ts
> +  public addLayer(layerRequest: LayerPostRequest): void {
Add Tests: take reference from here:
https://github.com/MapColonies/discrete-overseer-creator/blob/master/tests/unit/layers/models/progressModel.spec.ts#L42

2021-01-17 10:19 UTC, CL-SHLOMIKONCHA commented on src/common/interfaces.ts
> +export interface MapProxyJsonDocument {
fixed on 2b40b93

2021-01-17 10:20 UTC, CL-SHLOMIKONCHA commented on src/resourceName/models/layersManager.ts
> +    replaceYamlFileContent(yamlContent);
fixed on 19ee851

2021-01-17 10:20 UTC, CL-SHLOMIKONCHA commented on src/resourceName/models/layersManager.ts
> +  public addLayer(layerRequest: LayerPostRequest): void {
fixed on c72ad19

2021-01-17 12:40 UTC, asafMasa approved these changes

2021-01-17 12:41 UTC, merged